### ISSUE TITLE
flagging a DM - error 500 returned

### ISSUE THREAD

**Issue by InceptionTime** [roblox-dev-forum/simple-flags#3]
When flagging a DM, I am prompted with 500 error, sometimes the flag goes through and can be viewed in flag review, sometimes it doesn't.

**Comment by Kampfkarren** [comment]
![image](https://user-images.githubusercontent.com/3190756/67120103-706f1b80-f19d-11e9-8607-353a65c2a7da.png)
Super simple fix, coming soon
